version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.0

    working_directory: ~/computation

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python -m unittest discover .

      - store_artifacts:
          path: test-reports
          destination: test-reports
